# coding: utf-8

"""
    Onboarding API

     The onboarding API allows you to refer your customers and personal contacts to Brex. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from brex_onboarding_python_sdk.paths.v1_referrals.post import CreateNewReferralRaw
from brex_onboarding_python_sdk.paths.v1_referrals_id.get import GetByIdRaw
from brex_onboarding_python_sdk.paths.v1_referrals.get import GetListRaw
from brex_onboarding_python_sdk.paths.v1_referrals_id_document_upload.post import UploadDocumentRaw


class ReferralsApiRaw(
    CreateNewReferralRaw,
    GetByIdRaw,
    GetListRaw,
    UploadDocumentRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
