# coding: utf-8

"""
    Onboarding API

     The onboarding API allows you to refer your customers and personal contacts to Brex. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from brex_onboarding_python_sdk.paths.v1_referrals.post import CreateNewReferral
from brex_onboarding_python_sdk.paths.v1_referrals_id.get import GetById
from brex_onboarding_python_sdk.paths.v1_referrals.get import GetList
from brex_onboarding_python_sdk.paths.v1_referrals_id_document_upload.post import UploadDocument
from brex_onboarding_python_sdk.apis.tags.referrals_api_raw import ReferralsApiRaw


class ReferralsApi(
    CreateNewReferral,
    GetById,
    GetList,
    UploadDocument,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ReferralsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ReferralsApiRaw(api_client)
