# coding: utf-8

"""
    Onboarding API

     The onboarding API allows you to refer your customers and personal contacts to Brex. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from brex_onboarding_python_sdk import schemas  # noqa: F401


class DomesticInstruction(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Domestic ACH/wire instructions.
    """


    class MetaOapg:
        required = {
            "beneficiary_name",
            "account_type",
            "bank_account_number",
            "beneficiary_address",
            "bank_address",
            "bank_name",
            "bank_routing_number",
        }
        
        class properties:
            account_type = schemas.StrSchema
            bank_account_number = schemas.StrSchema
            bank_routing_number = schemas.StrSchema
            beneficiary_name = schemas.StrSchema
            beneficiary_address = schemas.StrSchema
            bank_name = schemas.StrSchema
            bank_address = schemas.StrSchema
            __annotations__ = {
                "account_type": account_type,
                "bank_account_number": bank_account_number,
                "bank_routing_number": bank_routing_number,
                "beneficiary_name": beneficiary_name,
                "beneficiary_address": beneficiary_address,
                "bank_name": bank_name,
                "bank_address": bank_address,
            }
    
    beneficiary_name: MetaOapg.properties.beneficiary_name
    account_type: MetaOapg.properties.account_type
    bank_account_number: MetaOapg.properties.bank_account_number
    beneficiary_address: MetaOapg.properties.beneficiary_address
    bank_address: MetaOapg.properties.bank_address
    bank_name: MetaOapg.properties.bank_name
    bank_routing_number: MetaOapg.properties.bank_routing_number
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["account_type"]) -> MetaOapg.properties.account_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bank_account_number"]) -> MetaOapg.properties.bank_account_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bank_routing_number"]) -> MetaOapg.properties.bank_routing_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["beneficiary_name"]) -> MetaOapg.properties.beneficiary_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["beneficiary_address"]) -> MetaOapg.properties.beneficiary_address: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bank_name"]) -> MetaOapg.properties.bank_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bank_address"]) -> MetaOapg.properties.bank_address: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["account_type", "bank_account_number", "bank_routing_number", "beneficiary_name", "beneficiary_address", "bank_name", "bank_address", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["account_type"]) -> MetaOapg.properties.account_type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bank_account_number"]) -> MetaOapg.properties.bank_account_number: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bank_routing_number"]) -> MetaOapg.properties.bank_routing_number: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["beneficiary_name"]) -> MetaOapg.properties.beneficiary_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["beneficiary_address"]) -> MetaOapg.properties.beneficiary_address: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bank_name"]) -> MetaOapg.properties.bank_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bank_address"]) -> MetaOapg.properties.bank_address: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["account_type", "bank_account_number", "bank_routing_number", "beneficiary_name", "beneficiary_address", "bank_name", "bank_address", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        beneficiary_name: typing.Union[MetaOapg.properties.beneficiary_name, str, ],
        account_type: typing.Union[MetaOapg.properties.account_type, str, ],
        bank_account_number: typing.Union[MetaOapg.properties.bank_account_number, str, ],
        beneficiary_address: typing.Union[MetaOapg.properties.beneficiary_address, str, ],
        bank_address: typing.Union[MetaOapg.properties.bank_address, str, ],
        bank_name: typing.Union[MetaOapg.properties.bank_name, str, ],
        bank_routing_number: typing.Union[MetaOapg.properties.bank_routing_number, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DomesticInstruction':
        return super().__new__(
            cls,
            *args,
            beneficiary_name=beneficiary_name,
            account_type=account_type,
            bank_account_number=bank_account_number,
            beneficiary_address=beneficiary_address,
            bank_address=bank_address,
            bank_name=bank_name,
            bank_routing_number=bank_routing_number,
            _configuration=_configuration,
            **kwargs,
        )
