# coding: utf-8

"""
    Onboarding API

     The onboarding API allows you to refer your customers and personal contacts to Brex. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from brex_onboarding_python_sdk import schemas  # noqa: F401


class IdentityDocumentType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Either a US SSN or US/international passport.
    """


    class MetaOapg:
        enum_value_to_name = {
            "SSN": "SSN",
            "PASSPORT": "PASSPORT",
        }
    
    @schemas.classproperty
    def SSN(cls):
        return cls("SSN")
    
    @schemas.classproperty
    def PASSPORT(cls):
        return cls("PASSPORT")
