# coding: utf-8

"""
    Onboarding API

     The onboarding API allows you to refer your customers and personal contacts to Brex. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from brex_onboarding_python_sdk import schemas  # noqa: F401


class IncorporationType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Incorporation type of the company referred.
    """
    
    @schemas.classproperty
    def C_CORP(cls):
        return cls("C_CORP")
    
    @schemas.classproperty
    def S_CORP(cls):
        return cls("S_CORP")
    
    @schemas.classproperty
    def B_CORP(cls):
        return cls("B_CORP")
    
    @schemas.classproperty
    def LLC(cls):
        return cls("LLC")
    
    @schemas.classproperty
    def LLP(cls):
        return cls("LLP")
    
    @schemas.classproperty
    def SOLE_PROP(cls):
        return cls("SOLE_PROP")
    
    @schemas.classproperty
    def ORG_501C3(cls):
        return cls("ORG_501C3")
    
    @schemas.classproperty
    def LP(cls):
        return cls("LP")
