# coding: utf-8

"""
    Onboarding API

     The onboarding API allows you to refer your customers and personal contacts to Brex. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from brex_onboarding_python_sdk import schemas  # noqa: F401


class Instruction(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Domestic and international ACH/wire instructions.
    """


    class MetaOapg:
        required = {
            "domestic",
            "international",
        }
        
        class properties:
        
            @staticmethod
            def domestic() -> typing.Type['DomesticInstruction']:
                return DomesticInstruction
        
            @staticmethod
            def international() -> typing.Type['InternationalInstruction']:
                return InternationalInstruction
            __annotations__ = {
                "domestic": domestic,
                "international": international,
            }
    
    domestic: 'DomesticInstruction'
    international: 'InternationalInstruction'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["domestic"]) -> 'DomesticInstruction': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["international"]) -> 'InternationalInstruction': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["domestic", "international", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["domestic"]) -> 'DomesticInstruction': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["international"]) -> 'InternationalInstruction': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["domestic", "international", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        domestic: 'DomesticInstruction',
        international: 'InternationalInstruction',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Instruction':
        return super().__new__(
            cls,
            *args,
            domestic=domestic,
            international=international,
            _configuration=_configuration,
            **kwargs,
        )

from brex_onboarding_python_sdk.model.domestic_instruction import DomesticInstruction
from brex_onboarding_python_sdk.model.international_instruction import InternationalInstruction
