# coding: utf-8

"""
    Onboarding API

     The onboarding API allows you to refer your customers and personal contacts to Brex. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from brex_onboarding_python_sdk import schemas  # noqa: F401


class Prong(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    When using `CONTROL` prong, the beneficial owner is a single individual with 
significant responsibility to control, manage, or direct a legal entity customer. This includes, an
executive officer or senior manager (Chief Executive Officer, Chief Financial Officer, Chief
Operating Officer, President), or any other individual who regularly performs similar
functions. 

Under the `OWNERSHIP` prong, a beneficial owner is each individual, if any, who, directly or
indirectly, through any contract, arrangement, understanding, relationship or otherwise, owns
25 percent or more of the equity interests of a legal entity customer. If a trust owns directly
or indirectly, through any contract, arrangement, understanding, relationship or otherwise, 25
percent or more of the equity interests of a legal entity customer, the beneficial owner is the
trustee.

Under the `BOTH` prong, the beneficial owner represents both.

    """
    
    @schemas.classproperty
    def OWNERSHIP(cls):
        return cls("OWNERSHIP")
    
    @schemas.classproperty
    def CONTROL(cls):
        return cls("CONTROL")
    
    @schemas.classproperty
    def BOTH(cls):
        return cls("BOTH")
